name: CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["CI - Build & Push to ACR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: internship-portal-aks
          resource-group: InternPortal-RG-India

      - name: Deploy new image
        run: |
          kubectl set image deployment/internship-portal-app internship-portal-app=internshipportalacr.azurecr.io/internship-portal-app:${{ github.run_number }}
          kubectl rollout status deployment/internship-portal-app
