name: CI - Build & Push to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name internshipportalacr

      - name: Build Docker image
        run: docker build -t internshipportalacr.azurecr.io/internship-portal-app:${{ github.run_number }} .

      - name: Push image to ACR
        run: docker push internshipportalacr.azurecr.io/internship-portal-app:${{ github.run_number }}

      - name: Save image tag for CD pipeline
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

